hints = [
    "Mobile OS by Google",
    "Superhero team from Marvel",
    "Used to carry items",
    "Mysterious triangle in the ocean",
    "Container for liquids",
    "Light gentle wind",
    "Structure to cross water",
    "Device used to take photos",
    "A large fortified building",
    "Sweet from cocoa beans",
    "Round shape with no corners",
    "Lost her slipper at midnight",
    "Sweet baked treat",
    "Serious risk or harm",
    "Dry sandy area",
    "Precious stone, hardest material",
    "Medical professional",
    "Smart marine mammal",
    "Mythical fire-breathing creature",
    "Famous vampire character",
    "Famous physicist with wild hair",
    "Largest land animal",
    "World’s highest mountain",
    "Popular social networking site",
    "Luxury sports car brand",
    "Network security system",
    "A plant known for beauty and fragrance",
    "Large area covered with trees",
    "Game with goals and a round ball",
    "Someone you trust and like",
    "Very cold, turned into ice",
    "Collection of stars and planets",
    "Place where plants grow",
    "Stringed musical instrument",
    "Computer intruder or coder",
    "School of witchcraft and wizardry",
    "One who hunts animals",
    "Land surrounded by water",
    "Batman’s nemesis",
    "Dinosaur-themed movie era",
    "Dense tropical forest",
    "Australian animal with a pouch",
    "A young cat",
    "Portable computer",
    "Place full of books",
    "Attracts iron and steel",
    "Half woman, half fish",
    "Block-building game",
    "Reflects your image",
    "A primate often in trees",
    "Light from the night sky",
    "Female parent",
    "High landform with steep sides",
    "Large body of saltwater",
    "International sports event",
    "A citrus fruit",
    "Cucumber preserved in vinegar",
    "Yellow Pokémon",
    "Italian dish with cheese and toppings",
    "A celestial body orbiting a star",
    "A royal male",
    "A popular programming language",
    "Colorful arc in the sky",
    "To save from danger",
    "Flowing water body",
    "Machine with human-like actions",
    "Eight-legged web-spinner",
    "World's largest hot desert",
    "Place to learn",
    "Humans collectively",
    "Hidden knowledge",
    "Famous fictional detective",
    "A shiny gray precious metal",
    "Eight-legged arachnid",
    "Another celestial body",
    "Spicy seasoning",
    "Used for writing or drawing",
    "Cucumber preserved in vinegar",
    "Yellow Pokémon",
    "Underground train or sandwich chain",
    "Batman’s nemesis",
    "Place full of books",
    "Light from the night sky",
    "Half woman, half fish",
    "International sports event",
    "Network security system",
    "Lost her slipper at midnight",
    "Takes care of animals",
    "Smart marine mammal",
    "Luxury sports car brand",
    "Sweet from cocoa beans",
    "Block-building game",
    "Colorful bird with feathers",
    "Famous vampire character",
    "Mobile OS by Google",
    "Used to see stars",
    "Appears after rain",
    "Marine creature shaped like a star",
    "School of witchcraft and wizardry",
    "Mysterious triangle in the ocean",
    "Famous physicist with wild hair",
    "Dinosaur-themed movie era"
]
